name: inventory_system_fan

packages:
  - "."
  - "common_test"
  - "common"
  - "dependencies"
  - "fitur/*"

scripts:
  fast_test:
    run: melos exec "py test_script/fast_test.py"
sdkPath: .fvm/flutter_sdk
